Add alias for doind a NixOS build and analyzing with mods

diff --git a/modules/home/bash/bash_funcs b/modules/home/bash/bash_funcs
--- a/modules/home/bash/bash_funcs
+++ b/modules/home/bash/bash_funcs
@@ -1,104 +1,109 @@
 #!/usr/bin/env bash
 
 getCharmRepos() {
-	getRepos() {
-		gh repo list charmbracelet --visibility="$1" --json name
-	}
+    getRepos() {
+        gh repo list charmbracelet --visibility="$1" --json name
+    }
 
-	getAllRepos() {
-		printf '%s %s' "$(getRepos "public")" "$(getRepos "private")" | jq -s 'add'
-	}
+    getAllRepos() {
+        printf '%s %s' "$(getRepos "public")" "$(getRepos "private")" | jq -s 'add'
+    }
 
-	getAllRepos |
-		jq .[].name |
-		tr -d '"' |
-		sort
+    getAllRepos |
+        jq .[].name |
+        tr -d '"' |
+        sort
 }
 
 pickCharmRepo() {
-	getCharmRepos | gum filter --height=10 --header "$1"
+    getCharmRepos | gum filter --height=10 --header "$1"
 }
 
 charm_clone() {
-	local repo
-	repo="$(pickCharmRepo "Clone which Charm™ repo?")"
-	if [[ -z "$repo" ]]; then
-		printf "Okay, never mind.\n"
-		return 1
-	fi
-	git clone "git@github.com:charmbracelet/$repo" "$HOME/src/$repo"
+    local repo
+    repo="$(pickCharmRepo "Clone which Charm™ repo?")"
+    if [[ -z "$repo" ]]; then
+        printf "Okay, never mind.\n"
+        return 1
+    fi
+    git clone "git@github.com:charmbracelet/$repo" "$HOME/src/$repo"
 }
 
 go_get_charm() {
-	local repo
-	repo="$(pickCharmRepo "Which Charm™ repo do you want to ‘go get?’")"
-	if [[ -z "$repo" ]]; then
-		printf "Okay, never mind.\n"
-		return 1
-	fi
-	go get "github.com/charmbracelet/$repo"
+    local repo
+    repo="$(pickCharmRepo "Which Charm™ repo do you want to ‘go get?’")"
+    if [[ -z "$repo" ]]; then
+        printf "Okay, never mind.\n"
+        return 1
+    fi
+    go get "github.com/charmbracelet/$repo"
+}
+
+# Returns the number of CPU cores available on the system.
+num_cores() {
+    nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo "Could not determine core count"
 }
 
 which_os() {
-	case "$OSTYPE" in
-	darwin*)
-		printf "darwin"
-		;;
+    case "$OSTYPE" in
+    darwin*)
+        printf "darwin"
+        ;;
 
-	linux*)
-		if [[ -f "/etc/issue" ]]; then
-			issue=$(cat /etc/issue)
-			if [[ $issue =~ "NixOS" ]]; then
-				printf "nixos"
-			elif [[ $issue =~ "Void" ]]; then
-				printf "void"
-			elif [[ $issue =~ "Arch" ]]; then
-				printf "arch"
-			elif [[ $issue =~ "Debian" ]]; then
-				printf "debian"
-			else
-				printf "linux"
-			fi
-		fi
-		;;
-	esac
-	printf ""
+    linux*)
+        if [[ -f "/etc/issue" ]]; then
+            issue=$(cat /etc/issue)
+            if [[ $issue =~ "NixOS" ]]; then
+                printf "nixos"
+            elif [[ $issue =~ "Void" ]]; then
+                printf "void"
+            elif [[ $issue =~ "Arch" ]]; then
+                printf "arch"
+            elif [[ $issue =~ "Debian" ]]; then
+                printf "debian"
+            else
+                printf "linux"
+            fi
+        fi
+        ;;
+    esac
+    printf ""
 }
 
 command_exists() {
-	if command -v "$1" &>/dev/null; then
-		printf 1
-		return
-	fi
-	printf 0
+    if command -v "$1" &>/dev/null; then
+        printf 1
+        return
+    fi
+    printf 0
 }
 
 commands_exist() {
-	for arg in "$@"; do
-		if [[ ! command_exists != "$arg" ]]; then
-			printf '%s' "$arg"
-		fi
-	done
-	printf ""
+    for arg in "$@"; do
+        if [[ ! command_exists != "$arg" ]]; then
+            printf '%s' "$arg"
+        fi
+    done
+    printf ""
 }
 
 #shellcheck disable=1090
 decryptAndSource() {
-	command -v gpg >/dev/null 2>&1 &&
-		source <(gpg --decrypt <<<"$1" 2>/dev/null)
+    command -v gpg >/dev/null 2>&1 &&
+        source <(gpg --decrypt <<<"$1" 2>/dev/null)
 }
 
 gitdiff() {
-	if [[ $(which_os) == darwin ]]; then
-		opendiff
-	else
-		vimdiff
-	fi
+    if [[ $(which_os) == darwin ]]; then
+        opendiff
+    else
+        vimdiff
+    fi
 }
 
 remove_headerbar() {
-	case "$OSTYPE" in
-	linux*) xprop -format _MOTIF_WM_HINTS 32c -set _MOTIF_WM_HINTS 2 ;;
-	*) return ;;
-	esac
+    case "$OSTYPE" in
+    linux*) xprop -format _MOTIF_WM_HINTS 32c -set _MOTIF_WM_HINTS 2 ;;
+    *) return ;;
+    esac
 }
